on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    environment:
      name: prod
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install
        run: yarn install

      - name: Build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: yarn build:app

      - name: Netlify Settings
        uses: canastro/copy-file-action@master
        with:
          source: 'netlify.toml'
          target: 'build/netlify.toml'

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: build-artifact
          path: build

  deploy:
    environment:
      name: prod
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: build-artifact
          path: build

      - name: Deploy
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          build-dir: './build'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
